#!/usr/bin/env python3
"""
NodusNet Edge Node Setup Wizard

Interactive setup for edge nodes. Collects user inputs,
resolves geographic data, fetches local repeaters from RepeaterBook,
and generates .env + repeaters.json for the edge node.

Usage:
    python setup-edge.py                          # Interactive mode
    python setup-edge.py --zip 85001 --non-interactive  # Scripted mode
    python setup-edge.py --dry-run                # Preview without writing

Requires only Python 3.8+ stdlib (no pip install needed).
"""

import argparse
import hashlib
import json
import math
import os
import re
import socket
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

ZIPPOPOTAM_API = "https://api.zippopotam.us/us/{zip}"
USER_AGENT = "NodusNet-Setup/1.0 (+https://nodusrf.com; nodusrf@proton.me)"

# Path to bundled zip->metro CBSA mapping (generated by generate-zip-metro.py)
# Can be overridden via NODUSNET_ZIP_METRO_PATH env var (used by install-edge.sh)
ZIP_METRO_PATH = Path(
    os.environ.get("NODUSNET_ZIP_METRO_PATH", "")
    or str(Path(__file__).resolve().parent.parent / "src/nodus_edge/data/zip_metro.json")
)

# Offline repeater database (full RepeaterBook dataset, all bands)
REPEATERS_PATH = Path(
    os.environ.get("NODUSNET_REPEATERS_PATH", "")
    or os.environ.get("NODUSNET_REPEATERS_2M_PATH", "")  # legacy env var
    or str(Path(__file__).resolve().parent.parent / "src/nodus_edge/data/repeaters.json")
)

NATIONAL_SIMPLEX_2M_HZ = 146_520_000
NATIONAL_SIMPLEX_70CM_HZ = 446_000_000
DEFAULT_RADIUS_MILES = 50
CORE_FREQ_COUNT = 10

BAND_CONFIG = {
    "2m":   {"low_mhz": 144.0, "high_mhz": 148.0, "simplex_hz": NATIONAL_SIMPLEX_2M_HZ, "label": "2m (VHF)"},
    "70cm": {"low_mhz": 420.0, "high_mhz": 450.0, "simplex_hz": NATIONAL_SIMPLEX_70CM_HZ, "label": "70cm (UHF)"},
}

# RTL-SDR usable bandwidth (after FFT rolloff, ~90% of sample rate)
RTLSDR_USABLE_BW_HZ = 2_160_000  # ~2.16 MHz usable from 2.4 Msps

# Callsign regex: 1-2 letters, 1 digit, 1-3 letters (US format)
CALLSIGN_RE = re.compile(r"^[A-Za-z]{1,2}[0-9][A-Za-z]{1,3}$")
# Broader international format
CALLSIGN_BROAD_RE = re.compile(r"^[A-Za-z0-9]{3,7}$")

ZIP_RE = re.compile(r"^\d{5}$")

# Colors
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
BOLD = "\033[1m"
NC = "\033[0m"

STATE_ABBREV_TO_NAME = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
    "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine",
    "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska",
    "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico",
    "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
    "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island",
    "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas",
    "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def info(msg: str) -> None:
    print(f"  {GREEN}[INFO]{NC} {msg}")


def warn(msg: str) -> None:
    print(f"  {YELLOW}[WARN]{NC} {msg}")


def error(msg: str) -> None:
    print(f"  {RED}[ERROR]{NC} {msg}")


def _stdin_bail():
    """Exit with a helpful message when stdin is not interactive."""
    error("Cannot read input (stdin is not a terminal).")
    error("If you ran this via 'curl | bash', try downloading first:")
    error("  curl -fsSL https://raw.githubusercontent.com/nodusrf/nodus-edge/main/install.sh -o install.sh")
    error("  bash install.sh")
    sys.exit(1)


def prompt(question: str, default: str = "", validator=None) -> str:
    """Prompt user for input with optional default and validation."""
    # Bail immediately if stdin is not a terminal (piped/exhausted)
    if not sys.stdin.isatty():
        if default:
            return default
        _stdin_bail()
    suffix = f" [{default}]" if default else ""
    while True:
        try:
            sys.stdout.flush()
            answer = input(f"  {question}{suffix}: ").strip()
        except EOFError:
            _stdin_bail()
        if not answer and default:
            answer = default
        if validator:
            err = validator(answer)
            if err:
                error(err)
                continue
        return answer


def prompt_yn(question: str, default_yes: bool = True) -> bool:
    """Prompt for yes/no answer."""
    if not sys.stdin.isatty():
        return default_yes
    hint = "Y/n" if default_yes else "y/N"
    while True:
        try:
            sys.stdout.flush()
            answer = input(f"  {question} [{hint}]: ").strip().lower()
        except EOFError:
            return default_yes
        if not answer:
            return default_yes
        if answer in ("y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        error("Please enter y or n.")


def load_zip_metro() -> dict:
    """Load the bundled zip->metro CBSA mapping if available."""
    if not ZIP_METRO_PATH.exists():
        return {}
    try:
        with open(ZIP_METRO_PATH) as f:
            data = json.load(f)
        return data.get("zips", {})
    except (json.JSONDecodeError, KeyError):
        return {}


def lookup_metro(zip_code: str, city: str, zip_metro: dict) -> str:
    """Resolve metro slug from zip code using CBSA mapping, with city fallback."""
    # Try CBSA mapping first (handles Elkhorn->omaha, Scottsdale->phoenix)
    if zip_code in zip_metro:
        return zip_metro[zip_code]
    # Fallback: slugify the city name from the zip API
    return slugify_city(city)


def slugify_city(city: str) -> str:
    """Normalize city name to a slug (fallback when CBSA mapping misses)."""
    slug = city.lower()
    slug = re.sub(r"[^a-z0-9]", "", slug)
    return slug[:20]


def haversine_distance(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Distance between two points in miles."""
    R = 3959  # Earth radius in miles
    lat1_r, lat2_r = math.radians(lat1), math.radians(lat2)
    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = math.sin(dlat / 2) ** 2 + math.cos(lat1_r) * math.cos(lat2_r) * math.sin(dlon / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


# ---------------------------------------------------------------------------
# Step 1: Server Connection
# ---------------------------------------------------------------------------

def ask_server_connection(args) -> dict:
    """Auto-connect to NodusNet server. No user prompts needed.

    Users can disconnect later via the dashboard if they want standalone mode.
    """
    server = (args.server or "https://api.nodusrf.com").rstrip("/")

    # Test connectivity (informational only)
    try:
        req = Request(f"{server}/health")
        req.add_header("User-Agent", USER_AGENT)
        urlopen(req, timeout=5)
        info(f"Server: {server} (connected)")
    except Exception:
        info(f"Server: {server} (will connect when available)")

    return {
        "synapse_endpoint": server,
        "rem_endpoint": server,
    }


# ---------------------------------------------------------------------------
# Step 2: Location
# ---------------------------------------------------------------------------

def resolve_zip(zip_code: str) -> dict:
    """Resolve zip code via zippopotam.us API."""
    url = ZIPPOPOTAM_API.format(zip=zip_code)
    req = Request(url)
    req.add_header("User-Agent", USER_AGENT)

    with urlopen(req, timeout=10) as response:
        data = json.loads(response.read().decode("utf-8"))

    place = data["places"][0]
    return {
        "lat": float(place["latitude"]),
        "lon": float(place["longitude"]),
        "city": place["place name"],
        "state": place["state"],
        "state_abbrev": place["state abbreviation"],
    }


def ask_manual_location() -> dict:
    """Fall back to manual location entry."""
    print()
    warn("Enter your location manually:")

    def validate_float(v):
        try:
            float(v)
            return None
        except ValueError:
            return "Must be a number."

    def validate_state(v):
        if v.upper() not in STATE_ABBREV_TO_NAME:
            return "Unknown state abbreviation."
        return None

    lat = float(prompt("Latitude", validator=validate_float))
    lon = float(prompt("Longitude", validator=validate_float))
    city = prompt("City")
    state_abbrev = prompt("State abbreviation (e.g. AZ)", validator=validate_state).upper()
    state = STATE_ABBREV_TO_NAME[state_abbrev]

    return {
        "lat": lat,
        "lon": lon,
        "city": city,
        "state": state,
        "state_abbrev": state_abbrev,
    }


def ask_location(args, zip_metro: dict) -> dict:
    """Ask for zip code, resolve to location + metro."""
    if args.non_interactive:
        # Non-interactive: use CLI args
        if args.lat and args.lon and args.city and args.state:
            state_name = STATE_ABBREV_TO_NAME.get(args.state.upper(), args.state)
            loc = {
                "lat": args.lat, "lon": args.lon,
                "city": args.city, "state": state_name,
                "state_abbrev": args.state.upper(),
            }
            zip_code = args.zip or ""
        elif args.zip:
            if not ZIP_RE.match(args.zip):
                error(f"Invalid zip code: {args.zip} (must be exactly 5 digits)")
                sys.exit(1)
            try:
                loc = resolve_zip(args.zip)
            except HTTPError as e:
                if e.code == 404:
                    error(f"Zip code {args.zip} not found.")
                else:
                    error(f"Zip code API error: {e.code}")
                sys.exit(1)
            except (URLError, Exception) as e:
                error(f"Could not reach zip code API: {e}")
                error("Use --lat/--lon/--city/--state instead.")
                sys.exit(1)
            zip_code = args.zip
        else:
            error("Non-interactive mode requires --zip or --lat/--lon/--city/--state")
            sys.exit(1)

        metro = args.metro or lookup_metro(zip_code, loc["city"], zip_metro)
        loc["metro"] = metro
        return loc

    print()
    print(f"  {BOLD}Step 2: Location{NC}")
    print(f"  {'─' * 50}")
    print()

    zip_code = ""
    while True:
        zip_code = prompt("What is your zip code? (or 'manual' for manual entry)")

        if zip_code.lower() == "manual":
            loc = ask_manual_location()
            zip_code = ""
            break

        if not ZIP_RE.match(zip_code):
            error("Zip code must be exactly 5 digits.")
            continue

        try:
            loc = resolve_zip(zip_code)
            break
        except HTTPError as e:
            if e.code == 404:
                error(f"Zip code {zip_code} not found.")
            else:
                error(f"API error: {e.code}")
                if prompt_yn("Enter location manually?"):
                    loc = ask_manual_location()
                    zip_code = ""
                    break
        except (URLError, Exception) as e:
            warn(f"Could not reach zip code API: {e}")
            if prompt_yn("Enter location manually?"):
                loc = ask_manual_location()
                zip_code = ""
                break

    info(f"Location: {loc['city']}, {loc.get('state_abbrev', '')} ({loc['lat']:.4f}, {loc['lon']:.4f})")
    print()

    # Resolve metro via CBSA mapping, fall back to city name
    default_metro = lookup_metro(zip_code, loc["city"], zip_metro)
    cbsa_source = " (CBSA)" if zip_code in zip_metro else ""
    print(f"  Your metro area will be: {BOLD}{default_metro}{NC}{cbsa_source} ({loc['city']}, {loc.get('state_abbrev', '')})")
    choice = prompt("Is this correct? (y/n/custom metro name)", default="y")

    if choice.lower() in ("y", "yes", ""):
        loc["metro"] = default_metro
    elif choice.lower() in ("n", "no"):
        custom = prompt("Enter metro name")
        loc["metro"] = slugify_city(custom)
    else:
        # They typed a custom metro name directly
        loc["metro"] = slugify_city(choice)

    info(f"Metro: {loc['metro']}")
    return loc


# ---------------------------------------------------------------------------
# Step 3: Callsign
# ---------------------------------------------------------------------------

def _sanitize_callsign(raw: str) -> str:
    """Strip a callsign to alphanumeric only. Returns empty on garbage."""
    clean = re.sub(r"[^A-Za-z0-9]", "", raw).upper()
    if len(clean) < 3 or len(clean) > 7:
        return ""
    return clean


def ask_callsign(args) -> str:
    """Ask for operator callsign (optional)."""
    if args.non_interactive:
        return _sanitize_callsign(args.callsign or "")

    print()
    print(f"  {BOLD}Step 3: Callsign{NC}")
    print(f"  {'─' * 50}")
    print()

    callsign = prompt("What is your callsign? (optional, Enter to skip)")

    if not callsign:
        info("No callsign — node will be anonymous.")
        return ""

    callsign = callsign.upper()

    if CALLSIGN_RE.match(callsign):
        info(f"Callsign: {callsign}")
        return callsign

    if CALLSIGN_BROAD_RE.match(callsign):
        warn(f"{callsign} doesn't match standard US callsign format.")
        if prompt_yn("Use it anyway?"):
            return callsign
        return ""

    warn(f"{callsign} doesn't look like a valid callsign.")
    if prompt_yn("Use it anyway?", default_yes=False):
        return callsign
    return ""


# ---------------------------------------------------------------------------
# Step 4: Node ID
# ---------------------------------------------------------------------------

def derive_node_id(callsign: str, metro: str, mode: str = "fm") -> str:
    """Derive node ID from callsign, metro, and mode."""
    if callsign:
        return f"{callsign.lower()}-{mode}-{metro}"
    else:
        seed = f"{socket.gethostname()}-{time.time()}"
        h = hashlib.sha256(seed.encode()).hexdigest()[:4]
        return f"anon-{mode}-{metro}-{h}"


# ---------------------------------------------------------------------------
# Step 4b: Band Selection
# ---------------------------------------------------------------------------

def ask_band(args) -> tuple[str, list[str]]:
    """Ask which mode/band to monitor.

    Returns (mode, bands) where mode is 'fm' or 'aprs',
    and bands is a list of band keys for FM mode.
    """
    raw = args.band.lower().strip()
    if raw == "aprs":
        return "aprs", []
    elif raw == "both":
        bands = ["2m", "70cm"]
    elif raw in BAND_CONFIG:
        bands = [raw]
    else:
        bands = ["2m"]

    if args.non_interactive:
        return "fm", bands

    print()
    print(f"  {BOLD}Step 4b: Mode Selection{NC}")
    print(f"  {'─' * 50}")
    print()
    print(f"    [1] {BOLD}FM 2m{NC}    Voice repeater monitoring (VHF 144-148 MHz)")
    print(f"    [2] {BOLD}FM 70cm{NC}  Voice repeater monitoring (UHF 420-450 MHz)")
    print(f"    [3] {BOLD}FM Both{NC}  Voice on 2m + 70cm")
    print(f"    [4] {BOLD}APRS{NC}     Packet data on 144.390 MHz (Direwolf decoder)")
    print()

    choice = prompt("Select mode", default="1")

    if choice in ("2", "70cm", "70"):
        return "fm", ["70cm"]
    elif choice in ("3", "both"):
        return "fm", ["2m", "70cm"]
    elif choice in ("4", "aprs"):
        return "aprs", []
    return "fm", ["2m"]


# ---------------------------------------------------------------------------
# Step 5: Repeater Discovery
# ---------------------------------------------------------------------------

def load_offline_repeaters(bands: list[str] | None = None) -> list:
    """Load the bundled repeater database and filter to FM on-air in selected bands."""
    if bands is None:
        bands = ["2m"]
    path = REPEATERS_PATH
    if not path.exists():
        return []
    try:
        with open(path) as f:
            data = json.load(f)
        all_rptrs = data.get("repeaters", [])
        # Build frequency ranges from selected bands
        ranges = [(BAND_CONFIG[b]["low_mhz"], BAND_CONFIG[b]["high_mhz"]) for b in bands if b in BAND_CONFIG]
        filtered = []
        for r in all_rptrs:
            try:
                freq = float(r.get("Frequency", 0))
            except (ValueError, TypeError):
                continue
            if not any(lo <= freq <= hi for lo, hi in ranges):
                continue
            if r.get("FM Analog") == "No":
                continue
            if r.get("Operational Status") not in ("On-air", ""):
                continue
            filtered.append(r)
        return filtered
    except (json.JSONDecodeError, OSError):
        return []


def fetch_repeaters(lat: float, lon: float, state_name: str,
                    radius_miles: float = DEFAULT_RADIUS_MILES,
                    bands: list[str] | None = None) -> tuple:
    """Find FM repeaters near location from bundled offline data.

    Returns (repeaters_list, metadata_dict).
    """
    if bands is None:
        bands = ["2m"]
    band_label = " + ".join(bands)
    metadata = {
        "center_lat": lat,
        "center_lon": lon,
        "radius_miles": radius_miles,
        "fetched_at": datetime.now(timezone.utc).isoformat(),
        "source": "offline-bundle",
        "bands": bands,
    }

    print()
    info(f"Searching bundled repeater data for {band_label} repeaters within {radius_miles} miles...")

    all_repeaters = load_offline_repeaters(bands)
    if not all_repeaters:
        warn("Offline repeater database not found.")
        warn(f"Looked in: {REPEATERS_PATH}")
        metadata["total_repeaters"] = 0
        return [], metadata

    info(f"Loaded {len(all_repeaters)} US {band_label} FM repeaters from offline database.")

    # Filter by distance
    nearby = []
    for rptr in all_repeaters:
        try:
            rlat = float(rptr.get("Lat", 0))
            rlon = float(rptr.get("Long", 0))
            if rlat == 0 or rlon == 0:
                continue
            dist = haversine_distance(lat, lon, rlat, rlon)
            if dist <= radius_miles:
                rptr["_distance_miles"] = round(dist, 1)
                nearby.append(rptr)
        except (ValueError, TypeError):
            continue

    # Deduplicate by (Frequency, Callsign), sort by distance
    seen = set()
    unique = []
    for rptr in sorted(nearby, key=lambda x: x.get("_distance_miles", 9999)):
        key = (rptr.get("Frequency"), rptr.get("Callsign"))
        if key not in seen:
            seen.add(key)
            unique.append(rptr)

    metadata["total_repeaters"] = len(unique)
    info(f"Found {len(unique)} repeaters within {radius_miles} miles.")

    return unique, metadata


def split_frequencies(repeaters: list, bands: list[str] | None = None) -> tuple:
    """Split repeaters into core and candidate frequency lists.

    Returns (core_hz, candidate_hz).
    Core: national simplex(es) + top 10 closest active repeaters.
    Candidate: remaining repeaters within radius.
    """
    if bands is None:
        bands = ["2m"]
    core_hz = [BAND_CONFIG[b]["simplex_hz"] for b in bands if b in BAND_CONFIG]

    # Filter to operational repeaters
    active = [r for r in repeaters
              if r.get("Operational Status", "").strip().lower() in ("on-air", "")]

    for rptr in active[:CORE_FREQ_COUNT]:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            if freq_hz not in core_hz:
                core_hz.append(freq_hz)
        except (ValueError, KeyError):
            continue

    core_set = set(core_hz)
    candidate_hz = []
    for rptr in active[CORE_FREQ_COUNT:]:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            if freq_hz not in core_set:
                candidate_hz.append(freq_hz)
        except (ValueError, KeyError):
            continue

    return core_hz, candidate_hz


def check_bandwidth(frequencies: list, repeaters: list) -> tuple:
    """Check if frequencies fit within RTL-SDR usable bandwidth.

    Returns (fits: bool, span_mhz: float, max_mhz: float, over_freqs: list).
    over_freqs is a list of (freq_hz, callsign, distance) for frequencies
    that would need to be dropped to fit.
    """
    if len(frequencies) < 2:
        return True, 0.0, RTLSDR_USABLE_BW_HZ / 1_000_000, []

    sorted_freqs = sorted(frequencies)
    span = sorted_freqs[-1] - sorted_freqs[0]
    max_bw = RTLSDR_USABLE_BW_HZ
    fits = span <= max_bw

    over_freqs = []
    if not fits:
        # Identify which edge frequencies would need to be dropped.
        # Try trimming from the high end first, then low end.
        center = (sorted_freqs[0] + sorted_freqs[-1]) // 2
        half_bw = max_bw // 2
        for freq_hz in sorted_freqs:
            if freq_hz < center - half_bw or freq_hz > center + half_bw:
                # Find repeater info
                callsign = ""
                distance = ""
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                            callsign = rptr.get("Callsign", "")
                            distance = rptr.get("_distance_miles", "?")
                            break
                    except (ValueError, KeyError):
                        continue
                over_freqs.append((freq_hz, callsign, distance))

    return fits, span / 1_000_000, max_bw / 1_000_000, over_freqs


def ask_repeaters(args, lat: float, lon: float, state_name: str,
                  bands: list[str] | None = None) -> tuple:
    """Fetch repeaters and get user confirmation.

    Returns (core_hz, candidate_hz, repeaters, metadata).
    """
    if bands is None:
        bands = ["2m"]
    radius = args.radius
    band_label = " + ".join(bands)

    print()
    print(f"  {BOLD}Step 5: Repeater Discovery{NC}")
    print(f"  {'─' * 50}")

    repeaters, metadata = fetch_repeaters(lat, lon, state_name, radius, bands)
    core_hz, candidate_hz = split_frequencies(repeaters, bands)

    print()
    info(f"Found {len(repeaters)} repeaters in the {band_label} band within {radius} miles.")
    print()

    if core_hz:
        print(f"  {BOLD}Core frequencies (always monitored):{NC}")
        for freq_hz in core_hz:
            freq_mhz = freq_hz / 1_000_000
            # Find matching repeater info
            label = ""
            if freq_hz in (NATIONAL_SIMPLEX_2M_HZ, NATIONAL_SIMPLEX_70CM_HZ):
                label = "National simplex"
            else:
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                            cs = rptr.get("Callsign", "")
                            dist = rptr.get("_distance_miles", "?")
                            city = rptr.get("Nearest City", "")
                            label = f"{cs}  ({dist} mi) {city}"
                            break
                    except (ValueError, KeyError):
                        continue
            print(f"    {freq_mhz:>10.3f} MHz  {label}")

    if candidate_hz:
        print()
        print(f"  {BOLD}Candidate frequencies (promoted when active): {len(candidate_hz)}{NC}")
        # Show first 5 candidates
        for freq_hz in candidate_hz[:5]:
            freq_mhz = freq_hz / 1_000_000
            for rptr in repeaters:
                try:
                    if int(float(rptr["Frequency"]) * 1_000_000) == freq_hz:
                        cs = rptr.get("Callsign", "")
                        dist = rptr.get("_distance_miles", "?")
                        city = rptr.get("Nearest City", "")
                        print(f"    {freq_mhz:>10.3f} MHz  {cs}  ({dist} mi) {city}")
                        break
                except (ValueError, KeyError):
                    continue
        if len(candidate_hz) > 5:
            print(f"    ... and {len(candidate_hz) - 5} more")

    if not repeaters:
        warn("No 2m repeaters found in your area.")
        info("146.520 MHz (national simplex) will be your only core frequency.")
        info("You can add frequencies manually in the .env file later.")

    # Bandwidth check: do all core frequencies fit in one RTL-SDR?
    fits, span_mhz, max_mhz, over_freqs = check_bandwidth(core_hz, repeaters)
    if not fits:
        print()
        warn(f"SDR bandwidth exceeded: your core frequencies span {span_mhz:.1f} MHz,")
        warn(f"but one RTL-SDR dongle can only cover ~{max_mhz:.1f} MHz at a time.")
        print()
        print(f"  An SDR captures a continuous {BOLD}slice of spectrum{NC} — it's not like a")
        print(f"  radio that hops between frequencies. All your frequencies must fit")
        print(f"  within that slice, or the edge ones won't be received.")
        print()
        if over_freqs:
            print(f"  {BOLD}Frequencies outside the usable window:{NC}")
            for freq_hz, callsign, distance in over_freqs:
                label = f"{callsign}  ({distance} mi)" if callsign else ""
                print(f"    {RED}{freq_hz / 1_000_000:>10.3f} MHz{NC}  {label}")
        print()
        print(f"  Options:")
        print(f"    1. {BOLD}Drop the out-of-range frequencies{NC} to fit within one dongle")
        print(f"    2. {BOLD}Add a second RTL-SDR dongle{NC} to cover additional spectrum")
        print(f"    3. {BOLD}Keep them anyway{NC} (edge frequencies may have degraded reception)")
        print()

        if not args.non_interactive:
            choice = prompt("Choose (1/2/3)", default="3")
            if choice == "1":
                drop_set = {f for f, _, _ in over_freqs}
                core_hz = [f for f in core_hz if f not in drop_set]
                info(f"Trimmed to {len(core_hz)} core frequencies within SDR bandwidth.")
            elif choice == "2":
                info("Multi-dongle: configure the second dongle in .env after setup.")
                info("Set RECEPT_FM_AIRBAND_CENTER_FREQ_HZ to optimize placement.")

    if not args.non_interactive:
        print()
        if not prompt_yn("Accept these frequencies?"):
            info("You can edit frequencies in the .env file after setup.")

    return core_hz, candidate_hz, repeaters, metadata


# ---------------------------------------------------------------------------
# Step 5b: Spectrum Coverage Assessment
# ---------------------------------------------------------------------------

def fetch_metro_coverage(server_url: str, metro: str, node_id: str, api_key: str = "") -> dict:
    """Fetch existing coverage data for a metro from the Gateway.

    Returns coverage map dict or empty dict on failure.
    """
    url = f"{server_url.rstrip('/')}/v1/edge/coverage/{metro}/suggestions?node_id={node_id}"
    headers = {"User-Agent": USER_AGENT}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except Exception:
        return {}


def fetch_metro_map(server_url: str, metro: str, api_key: str = "") -> dict:
    """Fetch the full coverage map for a metro."""
    url = f"{server_url.rstrip('/')}/v1/edge/coverage/{metro}"
    headers = {"User-Agent": USER_AGENT}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        req = Request(url, headers=headers)
        with urlopen(req, timeout=10) as resp:
            return json.loads(resp.read().decode())
    except Exception:
        return {}


def classify_band_simple(freq_hz: int) -> str:
    """Classify frequency into band name."""
    mhz = freq_hz / 1_000_000
    if 144 <= mhz <= 148:
        return "2m"
    if 222 <= mhz <= 225:
        return "1.25m"
    if 420 <= mhz <= 450:
        return "70cm"
    if 50 <= mhz <= 54:
        return "6m"
    if mhz < 30:
        return "hf"
    return "other"


def ask_spectrum_assessment(
    args,
    server_url: str,
    api_key: str,
    metro: str,
    node_id: str,
    core_hz: list,
    candidate_hz: list,
    repeaters: list,
) -> tuple:
    """Show metro coverage assessment and let operator adjust frequencies.

    Returns (core_hz, candidate_hz) potentially modified.
    """
    if not server_url or args.non_interactive:
        return core_hz, candidate_hz

    print()
    print(f"  {BOLD}Step 5b: Spectrum Coverage Assessment{NC}")
    print(f"  {'─' * 50}")
    print()

    # Fetch metro coverage map
    info("Checking existing spectrum coverage in your metro...")
    coverage_map = fetch_metro_map(server_url, metro, api_key)

    if not coverage_map or coverage_map.get("node_count", 0) == 0:
        info("No other nodes in your metro yet. You're the first!")
        info("Your frequency selections look great.")
        return core_hz, candidate_hz

    node_count = coverage_map.get("node_count", 0)
    band_summary = coverage_map.get("band_summary", {})
    freq_details = coverage_map.get("frequency_details", [])

    info(f"{node_count} other node{'s' if node_count != 1 else ''} already active in your metro.")
    print()

    # Show band coverage summary
    print(f"  {BOLD}Current metro band coverage:{NC}")
    for band_id, band_label in [("2m", "2 Meter"), ("70cm", "70cm"), ("1.25m", "1.25m (220)")]:
        bs = band_summary.get(band_id, {})
        nodes = bs.get("nodes", 0)
        freqs = bs.get("frequencies", 0)
        if nodes > 0:
            print(f"    {band_label:12s}  {nodes} node{'s' if nodes != 1 else ''}, {freqs} frequencies")
        else:
            print(f"    {band_label:12s}  {YELLOW}no coverage{NC}")
    print()

    # Check for over-covered frequencies in our proposed list
    my_freq_set = set(core_hz + candidate_hz)
    over_covered = []
    uncovered_by_us = []

    for fd in freq_details:
        fhz = fd["frequency_hz"]
        nc = fd["node_count"]
        if fhz in my_freq_set and nc >= 3:
            over_covered.append((fhz, nc))

    if over_covered:
        print(f"  {YELLOW}{BOLD}Overlap detected:{NC}")
        for fhz, nc in over_covered:
            label = ""
            for rptr in repeaters:
                try:
                    if int(float(rptr["Frequency"]) * 1_000_000) == fhz:
                        label = rptr.get("Callsign", "")
                        break
                except (ValueError, KeyError):
                    continue
            print(f"    {fhz / 1_000_000:>10.3f} MHz  already covered by {nc} nodes  {label}")
        print()
        print(f"  These frequencies have strong coverage already.")
        print(f"  Consider swapping some for uncovered repeaters to maximize")
        print(f"  your metro's overall spectrum coverage.")
        print()

    # Find repeaters in our list that nobody else covers (good!)
    unique_freqs = []
    for fhz in core_hz:
        covered_by_others = any(fd["frequency_hz"] == fhz for fd in freq_details)
        if not covered_by_others:
            unique_freqs.append(fhz)

    if unique_freqs:
        print(f"  {GREEN}{BOLD}Unique coverage you'd add:{NC}")
        for fhz in unique_freqs[:5]:
            label = ""
            if fhz in (NATIONAL_SIMPLEX_2M_HZ, NATIONAL_SIMPLEX_70CM_HZ):
                label = "National simplex"
            else:
                for rptr in repeaters:
                    try:
                        if int(float(rptr["Frequency"]) * 1_000_000) == fhz:
                            label = rptr.get("Callsign", "")
                            break
                    except (ValueError, KeyError):
                        continue
            print(f"    {fhz / 1_000_000:>10.3f} MHz  {label}")
        if len(unique_freqs) > 5:
            print(f"    ... and {len(unique_freqs) - 5} more")
        print()

    # Ask user what to do
    print(f"  Options:")
    print(f"    1. {BOLD}Accept proposed frequencies{NC} (recommended)")
    print(f"    2. {BOLD}Pick your own{NC} from the full repeater list")
    print()

    choice = prompt("Choose (1/2)", default="1")

    if choice == "2":
        core_hz, candidate_hz = interactive_frequency_picker(
            repeaters, core_hz, candidate_hz, freq_details,
        )

    return core_hz, candidate_hz


def interactive_frequency_picker(
    repeaters: list,
    current_core: list,
    current_candidates: list,
    metro_coverage: list,
) -> tuple:
    """Let the operator pick frequencies interactively.

    Returns (core_hz, candidate_hz).
    """
    # Build a map of metro coverage for display
    coverage_count = {}
    for fd in metro_coverage:
        coverage_count[fd["frequency_hz"]] = fd["node_count"]

    print()
    print(f"  {BOLD}Available repeaters (sorted by distance):{NC}")
    print()
    print(f"  {'#':>3s}  {'Freq MHz':>10s}  {'Callsign':8s}  {'Dist':>5s}  {'Other':>5s}  {'Status'}")
    print(f"  {'─' * 55}")

    # Build selectable list
    simplex_freqs = [BAND_CONFIG[b]["simplex_hz"] for b in BAND_CONFIG]
    selectable = [{"frequency_hz": f, "label": "National simplex", "distance": 0} for f in simplex_freqs if f in core_hz + candidate_hz]

    for rptr in repeaters:
        try:
            freq_hz = int(float(rptr["Frequency"]) * 1_000_000)
            selectable.append({
                "frequency_hz": freq_hz,
                "label": rptr.get("Callsign", ""),
                "distance": rptr.get("_distance_miles", "?"),
                "city": rptr.get("Nearest City", ""),
            })
        except (ValueError, KeyError):
            continue

    for i, item in enumerate(selectable[:30], 1):
        fhz = item["frequency_hz"]
        freq_mhz = fhz / 1_000_000
        label = item.get("label", "")
        dist = item.get("distance", "")
        others = coverage_count.get(fhz, 0)
        in_core = "*" if fhz in current_core else " "
        others_str = f"{others}" if others > 0 else "-"
        print(f"  {i:>3d}  {freq_mhz:>10.3f}  {label:8s}  {str(dist):>5s}  {others_str:>5s}  {in_core}")

    if len(selectable) > 30:
        print(f"  ... {len(selectable) - 30} more available")

    print()
    print(f"  * = currently selected as core")
    print(f"  'Other' column shows how many other metro nodes cover that frequency")
    print()

    selection = prompt(
        "Enter frequency numbers to use as core (comma-separated, e.g. 1,3,5,7)",
        default=",".join(str(i) for i in range(1, min(11, len(selectable) + 1))),
    )

    try:
        indices = [int(x.strip()) - 1 for x in selection.split(",") if x.strip()]
        new_core = []
        for idx in indices:
            if 0 <= idx < len(selectable):
                fhz = selectable[idx]["frequency_hz"]
                if fhz not in new_core:
                    new_core.append(fhz)
        if new_core:
            # Remaining become candidates
            core_set = set(new_core)
            new_candidates = [
                item["frequency_hz"]
                for item in selectable
                if item["frequency_hz"] not in core_set
            ]
            info(f"Selected {len(new_core)} core frequencies, {len(new_candidates)} candidates.")
            return new_core, new_candidates
    except ValueError:
        warn("Invalid selection, keeping original frequencies.")

    return current_core, current_candidates


# ---------------------------------------------------------------------------
# Step 6: RTL-SDR Device Selection
# ---------------------------------------------------------------------------

def detect_rtlsdr_devices() -> list:
    """Detect RTL-SDR USB devices via lsusb."""
    import subprocess
    devices = []
    try:
        result = subprocess.run(
            ["lsusb"], capture_output=True, text=True, timeout=5,
        )
        for line in result.stdout.splitlines():
            # RTL2832U vendor:product IDs
            if "0bda:2838" in line or "0bda:2832" in line:
                devices.append(line.strip())
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    return devices


def ask_sdr_device(args) -> dict:
    """Detect and select RTL-SDR device."""
    if args.non_interactive:
        return {
            "device_index": args.sdr_device if args.sdr_device is not None else 0,
            "gain": args.sdr_gain if args.sdr_gain is not None else 40,
        }

    print()
    print(f"  {BOLD}Step 6: RTL-SDR Device{NC}")
    print(f"  {'─' * 50}")
    print()

    devices = detect_rtlsdr_devices()

    if not devices:
        warn("No RTL-SDR devices detected via USB.")
        info("Make sure your dongle is plugged in before starting the containers.")
        info("Using default: device index 0, gain 40")
        return {"device_index": 0, "gain": 40}

    if len(devices) == 1:
        info(f"Found 1 RTL-SDR: {devices[0]}")
        device_index = 0
    else:
        info(f"Found {len(devices)} RTL-SDR devices:")
        for i, dev in enumerate(devices):
            print(f"    [{i}] {dev}")
        print()
        idx = prompt(f"Which device to use for FM scanning? (0-{len(devices)-1})", default="0")
        try:
            device_index = int(idx)
            if device_index < 0 or device_index >= len(devices):
                device_index = 0
                warn(f"Invalid index, using 0")
        except ValueError:
            device_index = 0

    gain = prompt("RTL-SDR gain (0-49, or 'auto')", default="40")

    return {
        "device_index": device_index,
        "gain": gain,
    }


# ---------------------------------------------------------------------------
# Step 7: RF Environment (Squelch)
# ---------------------------------------------------------------------------

RF_PRESETS = {
    "1": ("Urban / Noisy", "Near repeater sites, lots of RF", 25, 8.0),
    "2": ("Suburban / Moderate", "Default, good balance", 15, 5.0),
    "3": ("Rural / Quiet", "Weak signals, low noise floor", 8, 3.0),
}


def scan_noise_floor(device_index: int = 0, gain: str = "40") -> dict | None:
    """Scan 2m band with rtl_power to measure noise floor.

    Runs a quick sweep of 144-148 MHz and computes the 25th-percentile
    power level as the noise floor estimate.  Maps the result to
    recommended squelch / SNR settings.

    Returns dict with noise_floor_db, squelch_threshold,
    airband_squelch_snr_db, and label — or None on failure.
    """
    import shutil
    import subprocess
    import tempfile

    if not shutil.which("rtl_power"):
        return None

    fd, csv_path = tempfile.mkstemp(suffix=".csv")
    os.close(fd)

    try:
        cmd = [
            "rtl_power",
            "-d", str(device_index),
            "-f", "144M:148M:25k",  # 2m band, 25 kHz bins
            "-i", "2",               # 2s integration per window
            "-1",                     # single sweep then exit
        ]
        if gain and str(gain).lower() != "auto":
            cmd.extend(["-g", str(gain)])
        cmd.append(csv_path)

        subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        # Parse CSV: date, time, Hz_low, Hz_high, Hz_step, samples, dB, dB, ...
        powers = []
        with open(csv_path) as f:
            for line in f:
                parts = line.strip().split(",")
                if len(parts) > 6:
                    for val in parts[6:]:
                        try:
                            powers.append(float(val.strip()))
                        except ValueError:
                            pass

        if not powers:
            return None

        return classify_noise_floor(powers)
    except (subprocess.TimeoutExpired, OSError):
        return None
    finally:
        try:
            os.unlink(csv_path)
        except OSError:
            pass


def classify_noise_floor(powers: list) -> dict:
    """Map a list of power readings (dB) to squelch recommendations.

    Uses the 25th percentile as the noise floor estimate to avoid
    active signals skewing the result upward.
    """
    powers_sorted = sorted(powers)
    idx_25 = max(0, len(powers_sorted) // 4)
    noise_floor = powers_sorted[idx_25]

    if noise_floor > -45:
        sq, snr, label = 30, 10.0, "Very noisy"
    elif noise_floor > -55:
        sq, snr, label = 25, 8.0, "Urban / Noisy"
    elif noise_floor > -65:
        sq, snr, label = 15, 5.0, "Suburban / Moderate"
    else:
        sq, snr, label = 8, 3.0, "Rural / Quiet"

    return {
        "noise_floor_db": round(noise_floor, 1),
        "squelch_threshold": sq,
        "airband_squelch_snr_db": snr,
        "label": label,
    }


def ask_rf_environment(args, sdr_config: dict | None = None) -> dict:
    """Set squelch defaults. No user prompt. Tunable via .env later."""
    squelch = args.squelch if args.squelch is not None else 15
    return {"squelch_threshold": squelch, "airband_squelch_snr_db": 5.0}


# ---------------------------------------------------------------------------
# Step 8: Transcription (Whisper)
# ---------------------------------------------------------------------------

def is_raspberry_pi() -> bool:
    """Detect if running on a Raspberry Pi (too slow for local Whisper)."""
    import platform
    arch = platform.machine()
    if arch not in ("aarch64", "armv7l"):
        return False
    # Check /proc/cpuinfo for Raspberry Pi
    try:
        with open("/proc/cpuinfo") as f:
            cpuinfo = f.read()
        if "Raspberry Pi" in cpuinfo or "BCM2" in cpuinfo:
            return True
    except OSError:
        pass
    # Check device-tree model
    try:
        with open("/proc/device-tree/model") as f:
            model = f.read()
        if "Raspberry Pi" in model:
            return True
    except OSError:
        pass
    # Fallback: aarch64 with < 4GB RAM is likely a Pi or similar SBC
    try:
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    mem_kb = int(line.split()[1])
                    if mem_kb < 4_000_000:
                        return True
                    break
    except (OSError, ValueError):
        pass
    return False


def ask_whisper(args) -> str:
    """Ask for Whisper transcription endpoint."""
    pi_detected = is_raspberry_pi()

    if args.non_interactive:
        if pi_detected and args.whisper_url is None:
            return "https://api.nodusrf.com/v1/edge/whisper"
        return args.whisper_url if args.whisper_url is not None else "http://whisper:8000"

    print()
    print(f"  {BOLD}Step 8: Transcription{NC}")
    print(f"  {'─' * 50}")
    print()

    if pi_detected:
        warn("Raspberry Pi detected — local Whisper is not supported.")
        info("Using NodusNet cloud transcription via Gateway.")
        print()
        default_url = args.whisper_url or "https://api.nodusrf.com/v1/edge/whisper"
    else:
        default_url = args.whisper_url if args.whisper_url is not None else "http://whisper:8000"

    url = prompt(
        "Whisper transcription endpoint",
        default=default_url,
    )

    if url:
        # Skip connectivity test for Docker internal DNS (container isn't running yet)
        if "://whisper:" in url:
            info(f"Using Docker internal DNS: {url}")
        else:
            # Test connectivity
            try:
                req = Request(url)
                req.add_header("User-Agent", USER_AGENT)
                urlopen(req, timeout=5)
                info(f"Whisper reachable at {url}")
            except Exception:
                warn(f"Could not reach {url} — you can fix this in .env later.")
    else:
        info("Transcription disabled. Set RECEPT_WHISPER_API_URL in .env to enable.")

    return url


# ---------------------------------------------------------------------------
# Step 9: Generate Output
# ---------------------------------------------------------------------------

ENV_TEMPLATE_FM = """\
# NodusNet Edge Node Configuration
# Generated by setup-edge.py on {generated_at}
# Node: {node_id} | Metro: {metro}

# ---- Identity ----
RECEPT_MODE=fm
RECEPT_NODE_ID={node_id}
RECEPT_METRO={metro}
RECEPT_CALLSIGN={callsign}

# ---- Scanner ----
RECEPT_FM_SCANNER_BACKEND=airband
RECEPT_FM_CORE_FREQUENCIES={core_frequencies}
RECEPT_FM_CANDIDATE_FREQUENCIES={candidate_frequencies}
RECEPT_FM_RTL_DEVICE_INDEX={device_index}
RECEPT_FM_GAIN={gain}
# Squelch: raise if you get static-only recordings, lower if missing weak signals
RECEPT_FM_SQUELCH_THRESHOLD={squelch_threshold}
RECEPT_FM_AIRBAND_SQUELCH_SNR_DB={airband_squelch_snr_db}

# ---- Server ----
NODUSNET_SERVER={server}

# ---- Transcription ----
RECEPT_WHISPER_API_URL={whisper_api_url}
RECEPT_TRANSCRIPTION_ENABLED={transcription_enabled}
WHISPER_MODEL={whisper_model}

# ---- Logging ----
RECEPT_LOG_LEVEL=INFO
"""

ENV_TEMPLATE_APRS = """\
# NodusNet Edge Node Configuration (APRS)
# Generated by setup-edge.py on {generated_at}
# Node: {node_id} | Metro: {metro}

# ---- Identity ----
RECEPT_MODE=aprs
RECEPT_NODE_ID={node_id}
RECEPT_METRO={metro}
RECEPT_CALLSIGN={callsign}

# ---- APRS ----
RECEPT_APRS_FREQUENCY_HZ=144390000
RECEPT_APRS_DEVICE_INDEX={device_index}

# ---- Server ----
NODUSNET_SERVER={server}

# ---- Logging ----
RECEPT_LOG_LEVEL=INFO
"""


def generate_env(output_dir: Path, config: dict) -> str:
    """Generate .env file content."""
    common = dict(
        generated_at=datetime.now(timezone.utc).isoformat(),
        node_id=config["node_id"],
        metro=config["metro"],
        callsign=config.get("callsign", ""),
        server=config.get("synapse_endpoint", ""),
        device_index=config.get("device_index", 0),
    )
    if config.get("mode") == "aprs":
        return ENV_TEMPLATE_APRS.format(**common)
    return ENV_TEMPLATE_FM.format(
        **common,
        core_frequencies=json.dumps(config.get("core_frequencies", [])),
        candidate_frequencies=json.dumps(config.get("candidate_frequencies", [])),
        whisper_api_url=config.get("whisper_api_url", ""),
        transcription_enabled="true" if config.get("whisper_api_url") else "false",
        whisper_model=config.get("whisper_model", "base"),
        gain=config.get("gain", 40),
        squelch_threshold=config.get("squelch_threshold", 30),
        airband_squelch_snr_db=config.get("airband_squelch_snr_db", 6.0),
    )


def write_output(args, config: dict, repeaters: list, metadata: dict):
    """Write .env and repeaters.json to output directory."""
    output_dir = Path(args.output_dir)
    is_aprs = config.get("mode") == "aprs"

    env_content = generate_env(output_dir, config)

    if args.dry_run:
        print()
        print(f"  {BOLD}[DRY-RUN] .env contents:{NC}")
        for line in env_content.splitlines():
            print(f"    {line}")
        if is_aprs:
            print()
            print(f"  {BOLD}[DRY-RUN] docker-compose.yml:{NC} rewritten for APRS (no Whisper)")
        else:
            print()
            print(f"  {BOLD}[DRY-RUN] repeaters.json:{NC} {len(repeaters)} repeaters")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    env_path = output_dir / ".env"
    env_path.write_text(env_content)
    info(f"Created {env_path}")

    if is_aprs:
        # Rewrite compose: remove whisper service and repeaters mount
        compose_path = output_dir / "docker-compose.yml"
        if compose_path.exists():
            aprs_compose = (
                "# NodusNet Edge — APRS mode (auto-generated)\n"
                "services:\n"
                "  nodus-edge:\n"
                "    image: nodusrf/nodus-edge:${NODUS_EDGE_TAG:-latest}\n"
                "    privileged: true\n"
                "    devices:\n"
                "      - /dev/bus/usb:/dev/bus/usb\n"
                "    env_file: .env\n"
                "    ports:\n"
                '      - "8073:8073"\n'
                "    volumes:\n"
                "      - ./data:/data\n"
                "      - ./.env:/app/.env\n"
                "    restart: unless-stopped\n"
                "    healthcheck:\n"
                '      test: ["CMD", "python", "-c",'
                ' "import urllib.request;'
                " urllib.request.urlopen('http://localhost:8082/health')\"]\n"
                "      interval: 30s\n"
                "      timeout: 5s\n"
                "      retries: 3\n"
            )
            compose_path.write_text(aprs_compose)
            info(f"Rewrote {compose_path} for APRS mode (no Whisper)")
    else:
        repeaters_data = json.dumps({"metadata": metadata, "repeaters": repeaters}, indent=2)
        rptr_path = output_dir / "repeaters.json"
        rptr_path.write_text(repeaters_data)
        info(f"Created {rptr_path}")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

def print_summary(config: dict, repeater_count: int, output_dir: str, dry_run: bool):
    """Print setup summary."""
    print()
    print("=" * 60)
    print(f"  {GREEN}{BOLD}NodusNet Edge Node — Setup Complete{NC}")
    print("=" * 60)
    print()

    is_aprs = config.get("mode") == "aprs"
    connection = "NodusNet (remote Synapse)" if config.get("synapse_endpoint") else "Standalone (local only)"

    print(f"  Node ID:       {BOLD}{config['node_id']}{NC}")
    print(f"  Metro:         {config['metro']} ({config['city']}, {config['state_abbrev']})")
    if config.get("callsign"):
        print(f"  Callsign:      {config['callsign']}")
    else:
        print(f"  Callsign:      (anonymous)")
    print(f"  Mode:          {'APRS (144.390 MHz)' if is_aprs else 'FM voice'}")
    print(f"  Connection:    {connection}")
    print()

    if not is_aprs:
        print(f"  Core freqs:    {len(config['core_frequencies'])} (always monitored)")
        print(f"  Candidate:     {len(config['candidate_frequencies'])} (promoted when active)")
        print(f"  Repeaters:     {repeater_count} saved")
        print()

    if not dry_run:
        print(f"  Files created:")
        print(f"    .env            -> {Path(output_dir) / '.env'}")
        if is_aprs:
            print(f"    compose     -> {Path(output_dir) / 'docker-compose.yml'} (APRS, no Whisper)")
        else:
            print(f"    repeaters.json  -> {Path(output_dir) / 'repeaters.json'}")
        print()
        print(f"  Next steps:")
        print(f"    1. docker compose pull")
        print(f"    2. docker compose up -d")
        print(f"    3. Dashboard:  http://localhost:8073")

    print()
    print("=" * 60)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="NodusNet Edge Node Setup Wizard",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="Examples:\n"
               "  python setup-edge.py                    Interactive setup\n"
               "  python setup-edge.py --zip 85001        Start with Phoenix zip\n"
               "  python setup-edge.py --zip 85001 --callsign W1AW --non-interactive\n"
               "  python setup-edge.py --dry-run          Preview without writing files\n",
    )
    parser.add_argument("--zip", help="Zip code (skip prompt)")
    parser.add_argument("--lat", type=float, help="Latitude (skip zip lookup)")
    parser.add_argument("--lon", type=float, help="Longitude (skip zip lookup)")
    parser.add_argument("--city", help="City name")
    parser.add_argument("--state", help="State abbreviation (e.g. AZ)")
    parser.add_argument("--callsign", help="Operator callsign")
    parser.add_argument("--metro", help="Metro slug override")
    parser.add_argument("--server", help="NodusNet server URL (empty string = standalone)")
    parser.add_argument("--api-key", help="NodusNet API key")
    parser.add_argument("--sdr-device", type=int, help="RTL-SDR device index (default: 0)")
    parser.add_argument("--sdr-gain", help="RTL-SDR gain (0-49 or 'auto', default: 40)")
    parser.add_argument("--squelch", type=int, help="Squelch threshold override (default: 30)")
    parser.add_argument("--auto-squelch", action="store_true",
                        help="Auto-detect squelch by scanning noise floor (requires rtl_power)")
    parser.add_argument("--whisper-url", help="Whisper API URL")
    parser.add_argument("--output-dir", default=".", help="Output directory (default: current)")
    parser.add_argument("--band", default="2m",
                        help="Band selection: 2m, 70cm, both, or aprs (default: 2m)")
    parser.add_argument("--radius", type=float, default=DEFAULT_RADIUS_MILES,
                        help=f"Repeater search radius in miles (default: {DEFAULT_RADIUS_MILES})")
    parser.add_argument("--non-interactive", action="store_true",
                        help="Skip all prompts, use defaults + args")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print config without writing files")
    return parser.parse_args()


def main():
    args = parse_args()

    # Banner
    print()
    print("=" * 60)
    print(f"  {BOLD}NodusNet Edge Node Setup{NC}")
    print("=" * 60)
    print()
    print("  This wizard configures a new edge node for NodusNet.")
    print("  Modes: FM voice monitoring or APRS packet data.")

    if args.dry_run:
        print()
        warn("DRY RUN MODE — no files will be written.")

    # Load CBSA zip->metro mapping
    zip_metro = load_zip_metro()
    if zip_metro:
        info(f"Loaded {len(zip_metro)} zip-to-metro mappings (CBSA)")
    else:
        warn("zip_metro.json not found — metro will be derived from city name.")
        info("Run: python scripts/generate-zip-metro.py to build it.")

    # Step 1: Server connection
    server_config = ask_server_connection(args)

    # Step 2: Location
    location = ask_location(args, zip_metro)

    # Step 3: Callsign
    callsign = ask_callsign(args)

    # Step 4: Mode / band selection
    mode, bands = ask_band(args)

    # Step 4b: Node ID (uses mode for naming)
    node_id = derive_node_id(callsign, location["metro"], mode)
    print()
    print(f"  {BOLD}Node Identity{NC}")
    print(f"  {'─' * 50}")
    print()
    info(f"Your node ID: {BOLD}{node_id}{NC}")

    if mode == "aprs":
        # APRS mode: no repeaters, no whisper, no squelch
        sdr_config = ask_sdr_device(args)

        config = {
            "mode": "aprs",
            "node_id": node_id,
            "metro": location["metro"],
            "callsign": callsign,
            "city": location["city"],
            "state_abbrev": location.get("state_abbrev", ""),
            "device_index": sdr_config["device_index"],
            **server_config,
        }
        repeaters = []
        metadata = {}
    else:
        # FM mode: full repeater + whisper pipeline
        core_hz, candidate_hz, repeaters, metadata = ask_repeaters(
            args, location["lat"], location["lon"], location["state"],
            bands=bands,
        )

        # Spectrum coverage assessment (if connected to NodusNet)
        server_url = server_config.get("synapse_endpoint", "")
        gateway_url = server_config.get("gateway_url", "")
        if not gateway_url and server_url:
            gateway_url = server_url.rsplit("/v1", 1)[0] if "/v1" in server_url else server_url
        if gateway_url:
            core_hz, candidate_hz = ask_spectrum_assessment(
                args,
                server_url=gateway_url,
                api_key=server_config.get("synapse_auth_token", ""),
                metro=location["metro"],
                node_id=node_id,
                core_hz=core_hz,
                candidate_hz=candidate_hz,
                repeaters=repeaters,
            )

        sdr_config = ask_sdr_device(args)
        rf_config = ask_rf_environment(args, sdr_config)
        whisper_url = ask_whisper(args)

        config = {
            "mode": "fm",
            "node_id": node_id,
            "metro": location["metro"],
            "callsign": callsign,
            "city": location["city"],
            "state_abbrev": location.get("state_abbrev", ""),
            "core_frequencies": core_hz,
            "candidate_frequencies": candidate_hz,
            "whisper_api_url": whisper_url,
            "whisper_auth_token": server_config.get("synapse_auth_token", "") if "nodusrf.com" in (whisper_url or "") or "nodusalert.ai" in (whisper_url or "") else "",
            "device_index": sdr_config["device_index"],
            "gain": sdr_config["gain"],
            **rf_config,
            **server_config,
        }

    # Write output
    print()
    print(f"  {BOLD}Generate Configuration{NC}")
    print(f"  {'─' * 50}")
    print()

    write_output(args, config, repeaters, metadata)

    # Summary
    print_summary(config, len(repeaters), args.output_dir, args.dry_run)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n\n  {YELLOW}Setup cancelled.{NC}\n")
        sys.exit(1)
